--- 
framework: mocha
postMerge: 
  pattern: 
    - "test/**/*.spec.jjs"
postRun: 
  command: 
    - "node --version"  
preMerge: 
  pattern: 
    - "test/**/*.spec.jjs"
preRun: 
  command: 
    - npm ci
