--- 
framework: mocha
postMerge: 
  pattern: 
    - "test/**/*.speefdec.js"
    - "test/specs/factorialShort.spec.js"
postRun: 
  command: 
    - "node --version"  
preMerge: 
  pattern: 
    - "test/**/*.spvffec.js"
    - "test/specs/factorialShort.spec.js"
preRun: 
  command: 
    - npm ci
version: 1.0.0
