--- 
framework: mocha
postMerge: 
  pattern: 
    - "test/**/*ss.spec.js"
postRun: 
  command: 
    - "node --version"  
preMerge: 
  pattern: 
    - "test/**/*sdd.spec.js"
preRun: 
  command: 
    - npm ci
version: 1.0.0
